{
 "title": "Logs serveurs",
 "description": "Universal and flexible dashboard for logging",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host_name",
    "label": "Serveur",
    "query": "label_values({host=~\".+\"}, host)"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)", "query": "error" }
  ]
 },
 "panels": [
  {
   "title": "Nombre Total de logs",
   "type": "grafana-singlestat-panel",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({host=~\"$host_name\", service !=\"loki\", service!=\"portainer_agent\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total de :  $searchable_pattern",
   "type": "grafana-singlestat-panel",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({host=~\"$host_name\", service!=\"loki\", service!=\"portainer_agent\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{host=~\"$host_name\", service!=\"loki\", service!=\"portainer_agent\"} |~ \"$searchable_pattern\""
    }
   ]
  },
  {
   "title": "Pourcentage de \"$searchable_pattern\"",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({host=~\"$host_name\", service!=\"loki\", container_name!=\"portainer_agent\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({host=~\"$host_name\", service!=\"loki\", container_name!=\"portainer_agent\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Répartition par serveurs",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({host=~\"$host_name\", service!=\"loki\", container_name!=\"portainer_agent\"} |~ \"(?i)$searchable_pattern\") [$__interval])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Répartition de \"$searchable_pattern\" par services",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({host=~\"$host_name\", service!=\"loki\", container_name!=\"portainer_agent\"} |~ \"(?i)$searchable_pattern\") [$__interval])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Historique de logs total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({host=~\"$host_name\", service!=\"loki\", service!=\"portainer_agent\"}) [$__interval])) by (host)"
    }
   ]
  },
  {
   "title": "Historique de : \"$searchable_pattern\"",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({host=~\"$host_name\", service!=\"loki\", service!=\"portainer_agent\"} |~ \"(?i)$searchable_pattern\") [$__interval])) by (service)"
    }
   ]
  }
 ]
}