{
 "title": "Homepage",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Server",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Globals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Problems",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Docker-Prod" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Containers updates",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "name": "sumSeries",
        "category": "Aggregate",
        "params": [],
        "defaultParams": []
       },
       "params": [],
       "text": "sumSeries()",
       "$$hashKey": "object:674"
      }
     ],
     "group": { "filter": "Docker-Prod" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "Number of containers to update" },
     "itemTag": { "filter": "Application: Updater" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Paquets updates",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "name": "sumSeries",
        "category": "Aggregate",
        "params": [],
        "defaultParams": []
       },
       "params": [],
       "text": "sumSeries()",
       "$$hashKey": "object:745"
      }
     ],
     "group": { "filter": "Docker-Prod" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "Number of paquets to update" },
     "itemTag": { "filter": "Application: Updater" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Backup status",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "name": "sumSeries",
        "category": "Aggregate",
        "params": [],
        "defaultParams": []
       },
       "params": [],
       "text": "sumSeries()",
       "$$hashKey": "object:892"
      }
     ],
     "group": { "filter": "Docker-Prod" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/tatus/" },
     "itemTag": { "filter": "/Application: BackupScript/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Containers",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "name": "sumSeries",
        "category": "Aggregate",
        "params": [],
        "defaultParams": []
       },
       "params": [],
       "text": "sumSeries()",
       "$$hashKey": "object:1111"
      }
     ],
     "group": { "filter": "Docker-Prod" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "Docker: Containers total" },
     "itemTag": { "filter": "Application: Docker" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Containers stopped",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "name": "sumSeries",
        "category": "Aggregate",
        "params": [],
        "defaultParams": []
       },
       "params": [],
       "text": "sumSeries()",
       "$$hashKey": "object:1253"
      }
     ],
     "group": { "filter": "Docker-Prod" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "Docker: Containers stopped" },
     "itemTag": { "filter": "Application: Docker" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Containers dead",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "name": "sumSeries",
        "category": "Aggregate",
        "params": [],
        "defaultParams": []
       },
       "params": [],
       "text": "sumSeries()",
       "$$hashKey": "object:1577"
      }
     ],
     "group": { "filter": "Docker-Prod" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/Dead/" },
     "itemTag": {
      "filter": "/Application: Docker: Container/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Containers paused",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "name": "sumSeries",
        "category": "Aggregate",
        "params": [],
        "defaultParams": []
       },
       "params": [],
       "text": "sumSeries()",
       "$$hashKey": "object:1186"
      }
     ],
     "group": { "filter": "Docker-Prod" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "Docker: Containers paused" },
     "itemTag": { "filter": "Application: Docker" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Zabbix problems", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Zabbix Alerts",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Docker-Prod" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "Application:Disk sda" },
     "trigger": { "filter": "/.*/" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "$Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "Server" },
  {
   "title": "Uptime",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 16 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$Server" },
     "item": { "filter": "System uptime" },
     "itemTag": { "filter": "Application: Status" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Problems",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$Server" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 0
     }
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$Server" },
     "item": { "filter": "CPU utilization" },
     "itemTag": { "filter": "Application: CPU" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$Server" },
     "item": { "filter": "Memory utilization" },
     "itemTag": { "filter": "Application: Memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Storage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:495",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "System" ],
       "text": "setAlias(System)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$Server" },
     "item": { "filter": "/: Space utilization" },
     "itemTag": { "filter": "Application: Filesystem /" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:516",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Data" ],
       "text": "setAlias(Data)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$Server" },
     "item": { "filter": "/_data: Space utilization" },
     "itemTag": { "filter": "Application: Filesystem /_data" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Updates",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:269",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$Server" },
     "item": { "filter": "/to update/" },
     "itemTag": { "filter": "Application: Updater" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Containers",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$Server" },
     "item": { "filter": "Docker: Containers total" },
     "itemTag": { "filter": "Application: Docker" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Paused",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:806",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$Server" },
     "item": { "filter": "Docker: Containers paused" },
     "itemTag": { "filter": "Application: Docker" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Stopped",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:873",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$Server" },
     "item": { "filter": "Docker: Containers stopped" },
     "itemTag": { "filter": "Application: Docker" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Dead",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:940",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$Server" },
     "item": { "filter": "/Dead/" },
     "itemTag": {
      "filter": "/Application: Docker: Container/"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Backup Status",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:621",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$Server" },
     "item": { "filter": "/tatus/" },
     "itemTag": { "filter": "/Application: BackupScript/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Last backup",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:394",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$Server" },
     "item": { "filter": "Latest backup date" },
     "itemTag": { "filter": "Application: BackupScript" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}