{
 "title": "Backups",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SERVER",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Latest backup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "BackupScript" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$SERVER" },
     "item": { "filter": "Backup Status" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Backups status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/BackupScript */" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAliasByRegex",
        "params": [
         { "name": "aliasByRegex", "type": "string" }
        ]
       },
       "params": [ "(?<=\\:\\s)([\\w\\-]+)" ],
       "text": "setAliasByRegex((?<=\\:\\s)([\\w\\-]+))",
       "$$hashKey": "object:32"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$SERVER" },
     "item": { "filter": "/status*/" },
     "itemTag": { "filter": "Application: /BackupScript */" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Folders count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "BackupScript" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$SERVER" },
     "item": { "filter": "Folders backup count" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Folders errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "BackupScript" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$SERVER" },
     "item": { "filter": "Folders backup errors" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Folders total size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "BackupScript - Folders" },
     "functions": [
      {
       "def": {
        "name": "sumSeries",
        "category": "Aggregate",
        "params": [],
        "defaultParams": []
       },
       "params": [],
       "text": "sumSeries()",
       "added": false,
       "$$hashKey": "object:220"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$SERVER" },
     "item": { "filter": "/.*/" },
     "itemTag": {
      "filter": "Application: BackupScript - Folders"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Folders list",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "BackupScript" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$SERVER" },
     "item": { "filter": "Folders backup list" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "BackupScript" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$SERVER" },
     "item": { "filter": "Backup time" },
     "itemTag": { "filter": "Application: BackupScript" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Backups status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "BackupScript" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()",
       "$$hashKey": "object:381"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$SERVER" },
     "item": { "filter": "/Backup Status|Backup Errors/" },
     "itemTag": { "filter": "Application: BackupScript" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Databases count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "BackupScript" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$SERVER" },
     "item": { "filter": "Databases backup count" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Databases errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "BackupScript" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$SERVER" },
     "item": { "filter": "Databases backup errors" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Databases total size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "BackupScript - Databases" },
     "functions": [
      {
       "$$hashKey": "object:282",
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$SERVER" },
     "item": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Databases list",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "BackupScript" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$SERVER" },
     "item": { "filter": "Databases backup list" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Backup size",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "BackupScript - Folders" },
     "functions": [
      {
       "def": {
        "name": "setAliasByRegex",
        "category": "Alias",
        "params": [
         { "name": "aliasByRegex", "type": "string" }
        ],
        "defaultParams": []
       },
       "params": [ "(?<=\\:\\s)([\\w\\-]+)" ],
       "text": "setAliasByRegex((?<=\\:\\s)([\\w\\-]+))",
       "added": false,
       "$$hashKey": "object:272"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$SERVER" },
     "item": { "filter": "/.*/" },
     "itemTag": {
      "filter": "Application: BackupScript - Folders"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "BackupScript - Databases" },
     "functions": [
      {
       "def": {
        "name": "setAliasByRegex",
        "category": "Alias",
        "params": [
         { "name": "aliasByRegex", "type": "string" }
        ],
        "defaultParams": []
       },
       "params": [ "(?<=\\:\\s)([\\w\\-]+)" ],
       "text": "setAliasByRegex((?<=\\:\\s)([\\w\\-]+))",
       "added": false,
       "$$hashKey": "object:274"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$SERVER" },
     "item": { "filter": "/.*/" },
     "itemTag": {
      "filter": "Application: BackupScript - Databases"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Folders size",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "BackupScript - Folders" },
     "functions": [
      {
       "def": {
        "name": "setAliasByRegex",
        "category": "Alias",
        "params": [
         { "name": "aliasByRegex", "type": "string" }
        ],
        "defaultParams": []
       },
       "params": [ "(?<=\\:\\s)([\\w\\-]+)" ],
       "text": "setAliasByRegex((?<=\\:\\s)([\\w\\-]+))",
       "$$hashKey": "object:327"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$SERVER" },
     "item": { "filter": "/.*/" },
     "itemTag": {
      "filter": "Application: BackupScript - Folders"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Databases size",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "BackupScript - Databases" },
     "functions": [
      {
       "def": {
        "name": "setAliasByRegex",
        "category": "Alias",
        "params": [
         { "name": "aliasByRegex", "type": "string" }
        ],
        "defaultParams": []
       },
       "params": [ "(?<=\\:\\s)([\\w\\-]+)" ],
       "text": "setAliasByRegex((?<=\\:\\s)([\\w\\-]+))",
       "added": false,
       "$$hashKey": "object:355"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$SERVER" },
     "item": { "filter": "/.*/" },
     "itemTag": {
      "filter": "Application: BackupScript - Databases"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Backup process time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "BackupScript" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$SERVER" },
     "item": { "filter": "Backup time" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Backup total size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "application": { "filter": "BackupScript" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$SERVER" },
     "item": { "filter": "Backup total size" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Storage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/BackupScript */" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAliasByRegex",
        "params": [
         { "name": "aliasByRegex", "type": "string" }
        ]
       },
       "params": [ "(?<=\\:\\s)([\\w\\-]+)" ],
       "text": "setAliasByRegex((?<=\\:\\s)([\\w\\-]+))",
       "$$hashKey": "object:167"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$SERVER" },
     "item": { "filter": "/pourcent */" },
     "itemTag": { "filter": "Application: /BackupScript */" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Storage free",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "/BackupScript */" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAliasByRegex",
        "params": [
         { "name": "aliasByRegex", "type": "string" }
        ]
       },
       "params": [ "(?<=\\:\\s)([\\w\\-]+)" ],
       "text": "setAliasByRegex((?<=\\:\\s)([\\w\\-]+))",
       "$$hashKey": "object:59"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$SERVER" },
     "item": { "filter": "/free */" },
     "itemTag": { "filter": "Application: /BackupScript */" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}